kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.pnpm-store

  - name: build
    image: node:16-buster
    commands:
      - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
      - pnpm config set store-dir .pnpm-store
      - pnpm i && pnpm lint
      # - pnpm test
      - pnpm build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./.pnpm-store

  - name: image
    image: plugins/docker
    settings:
      registry: registry.okami101.io
      repo: registry.okami101.io/adr1enbe4udou1n/vue-ts-realworld
      tags: latest
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password

  - name: deploy
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: kube_server
      kubernetes_cert:
        from_secret: kube_ca
      kubernetes_token:
        from_secret: kube_token
    commands:
      - kubectl rollout restart deployments/vue-ts -n conduit

trigger:
  event:
    - push
    - pull_request
