/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertMessage: typeof import('./src/components/AlertMessage.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ArticlesNav: typeof import('./src/components/ArticlesNav.vue')['default']
    AuthorLayout: typeof import('./src/components/AuthorLayout.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    CommentCard: typeof import('./src/components/CommentCard.vue')['default']
    CommentNew: typeof import('./src/components/CommentNew.vue')['default']
    FavoriteArticle: typeof import('./src/components/Actions/FavoriteArticle.vue')['default']
    FollowProfile: typeof import('./src/components/Actions/FollowProfile.vue')['default']
    FormValidation: typeof import('./src/components/FormValidation.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeLayout: typeof import('./src/components/HomeLayout.vue')['default']
    MarkdownViewer: typeof import('./src/components/MarkdownViewer.vue')['default']
    OffsetPagination: typeof import('./src/components/OffsetPagination.vue')['default']
    PostAuthor: typeof import('./src/components/PostAuthor.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    PostsList: typeof import('./src/components/PostsList.vue')['default']
    ProfileCard: typeof import('./src/components/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuccessMessage: typeof import('./src/components/SuccessMessage.vue')['default']
    TagInput: typeof import('./src/components/Inputs/TagInput.vue')['default']
    TagsList: typeof import('./src/components/TagsList.vue')['default']
  }
}
