sonar.projectKey=vue-ts-realworld
sonar.projectName=Vue TypeScript RealWorld
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/__tests__/**,src/**/*.spec.ts,src/**/*.test.ts,src/**/*.spec.tsx,src/**/*.test.tsx
sonar.exclusions=src/**/__tests__/**,src/**/*.spec.ts,src/**/*.test.ts,src/**/*.spec.tsx,src/**/*.test.tsx,src/api/client/**
sonar.typescript.tsconfigPaths=tsconfig.app.json,tsconfig.node.json,tsconfig.vitest.json
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/**/__tests__/**,src/**/*.spec.ts,src/**/*.test.ts,src/**/*.spec.tsx,src/**/*.test.tsx
