/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/articles/[slug]/': RouteRecordInfo<'/articles/[slug]/', '/articles/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/articles/[slug]/edit': RouteRecordInfo<'/articles/[slug]/edit', '/articles/:slug/edit', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/articles/create': RouteRecordInfo<'/articles/create', '/articles/create', Record<never, never>, Record<never, never>>,
    '/feed': RouteRecordInfo<'/feed', '/feed', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/profiles/[username]/': RouteRecordInfo<'/profiles/[username]/', '/profiles/:username', { username: ParamValue<true> }, { username: ParamValue<false> }>,
    '/profiles/[username]/favorites': RouteRecordInfo<'/profiles/[username]/favorites', '/profiles/:username/favorites', { username: ParamValue<true> }, { username: ParamValue<false> }>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
  }
}
