// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateArticleCommentData, CreateArticleCommentErrors, CreateArticleCommentResponses, CreateArticleData, CreateArticleErrors, CreateArticleFavoriteData, CreateArticleFavoriteErrors, CreateArticleFavoriteResponses, CreateArticleResponses, CreateUserData, CreateUserErrors, CreateUserResponses, DeleteArticleCommentData, DeleteArticleCommentErrors, DeleteArticleCommentResponses, DeleteArticleData, DeleteArticleErrors, DeleteArticleFavoriteData, DeleteArticleFavoriteErrors, DeleteArticleFavoriteResponses, DeleteArticleResponses, FollowUserByUsernameData, FollowUserByUsernameErrors, FollowUserByUsernameResponses, GetArticleCommentsData, GetArticleCommentsErrors, GetArticleCommentsResponses, GetArticleData, GetArticleErrors, GetArticleResponses, GetArticlesData, GetArticlesErrors, GetArticlesFeedData, GetArticlesFeedErrors, GetArticlesFeedResponses, GetArticlesResponses, GetCurrentUserData, GetCurrentUserErrors, GetCurrentUserResponses, GetProfileByUsernameData, GetProfileByUsernameErrors, GetProfileByUsernameResponses, GetTagsData, GetTagsErrors, GetTagsResponses, LoginData, LoginErrors, LoginResponses, UnfollowUserByUsernameData, UnfollowUserByUsernameErrors, UnfollowUserByUsernameResponses, UpdateArticleData, UpdateArticleErrors, UpdateArticleResponses, UpdateCurrentUserData, UpdateCurrentUserErrors, UpdateCurrentUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get current user
 *
 * Gets the currently logged-in user
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError> => (options?.client ?? client).get<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user',
    ...options
});

/**
 * Update current user
 *
 * Updated user information for current user
 */
export const updateCurrentUser = <ThrowOnError extends boolean = false>(options: Options<UpdateCurrentUserData, ThrowOnError>): RequestResult<UpdateCurrentUserResponses, UpdateCurrentUserErrors, ThrowOnError> => (options.client ?? client).put<UpdateCurrentUserResponses, UpdateCurrentUserErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register a new user
 *
 * Register a new user
 */
export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> => (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
    url: '/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Existing user login
 *
 * Login for existing user
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/users/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a profile
 *
 * Get a profile of a user of the system. Auth is optional
 */
export const getProfileByUsername = <ThrowOnError extends boolean = false>(options: Options<GetProfileByUsernameData, ThrowOnError>): RequestResult<GetProfileByUsernameResponses, GetProfileByUsernameErrors, ThrowOnError> => (options.client ?? client).get<GetProfileByUsernameResponses, GetProfileByUsernameErrors, ThrowOnError>({ url: '/profiles/{username}', ...options });

/**
 * Unfollow a user
 *
 * Unfollow a user by username
 */
export const unfollowUserByUsername = <ThrowOnError extends boolean = false>(options: Options<UnfollowUserByUsernameData, ThrowOnError>): RequestResult<UnfollowUserByUsernameResponses, UnfollowUserByUsernameErrors, ThrowOnError> => (options.client ?? client).delete<UnfollowUserByUsernameResponses, UnfollowUserByUsernameErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/profiles/{username}/follow',
    ...options
});

/**
 * Follow a user
 *
 * Follow a user by username
 */
export const followUserByUsername = <ThrowOnError extends boolean = false>(options: Options<FollowUserByUsernameData, ThrowOnError>): RequestResult<FollowUserByUsernameResponses, FollowUserByUsernameErrors, ThrowOnError> => (options.client ?? client).post<FollowUserByUsernameResponses, FollowUserByUsernameErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/profiles/{username}/follow',
    ...options
});

/**
 * Get tags
 *
 * Get tags. Auth not required
 */
export const getTags = <ThrowOnError extends boolean = false>(options?: Options<GetTagsData, ThrowOnError>): RequestResult<GetTagsResponses, GetTagsErrors, ThrowOnError> => (options?.client ?? client).get<GetTagsResponses, GetTagsErrors, ThrowOnError>({ url: '/tags', ...options });

/**
 * Get recent articles globally
 *
 * Get most recent articles globally. Use query parameters to filter results. Auth is optional
 */
export const getArticles = <ThrowOnError extends boolean = false>(options?: Options<GetArticlesData, ThrowOnError>): RequestResult<GetArticlesResponses, GetArticlesErrors, ThrowOnError> => (options?.client ?? client).get<GetArticlesResponses, GetArticlesErrors, ThrowOnError>({ url: '/articles', ...options });

/**
 * Create an article
 *
 * Create an article. Auth is required
 */
export const createArticle = <ThrowOnError extends boolean = false>(options: Options<CreateArticleData, ThrowOnError>): RequestResult<CreateArticleResponses, CreateArticleErrors, ThrowOnError> => (options.client ?? client).post<CreateArticleResponses, CreateArticleErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/articles',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get recent articles from users you follow
 *
 * Get most recent articles from users you follow. Use query parameters to limit. Auth is required
 */
export const getArticlesFeed = <ThrowOnError extends boolean = false>(options?: Options<GetArticlesFeedData, ThrowOnError>): RequestResult<GetArticlesFeedResponses, GetArticlesFeedErrors, ThrowOnError> => (options?.client ?? client).get<GetArticlesFeedResponses, GetArticlesFeedErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/articles/feed',
    ...options
});

/**
 * Delete an article
 *
 * Delete an article. Auth is required
 */
export const deleteArticle = <ThrowOnError extends boolean = false>(options: Options<DeleteArticleData, ThrowOnError>): RequestResult<DeleteArticleResponses, DeleteArticleErrors, ThrowOnError> => (options.client ?? client).delete<DeleteArticleResponses, DeleteArticleErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/articles/{slug}',
    ...options
});

/**
 * Get an article
 *
 * Get an article. Auth not required
 */
export const getArticle = <ThrowOnError extends boolean = false>(options: Options<GetArticleData, ThrowOnError>): RequestResult<GetArticleResponses, GetArticleErrors, ThrowOnError> => (options.client ?? client).get<GetArticleResponses, GetArticleErrors, ThrowOnError>({ url: '/articles/{slug}', ...options });

/**
 * Update an article
 *
 * Update an article. Auth is required
 */
export const updateArticle = <ThrowOnError extends boolean = false>(options: Options<UpdateArticleData, ThrowOnError>): RequestResult<UpdateArticleResponses, UpdateArticleErrors, ThrowOnError> => (options.client ?? client).put<UpdateArticleResponses, UpdateArticleErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/articles/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Unfavorite an article
 *
 * Unfavorite an article. Auth is required
 */
export const deleteArticleFavorite = <ThrowOnError extends boolean = false>(options: Options<DeleteArticleFavoriteData, ThrowOnError>): RequestResult<DeleteArticleFavoriteResponses, DeleteArticleFavoriteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteArticleFavoriteResponses, DeleteArticleFavoriteErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/articles/{slug}/favorite',
    ...options
});

/**
 * Favorite an article
 *
 * Favorite an article. Auth is required
 */
export const createArticleFavorite = <ThrowOnError extends boolean = false>(options: Options<CreateArticleFavoriteData, ThrowOnError>): RequestResult<CreateArticleFavoriteResponses, CreateArticleFavoriteErrors, ThrowOnError> => (options.client ?? client).post<CreateArticleFavoriteResponses, CreateArticleFavoriteErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/articles/{slug}/favorite',
    ...options
});

/**
 * Get comments for an article
 *
 * Get the comments for an article. Auth is optional
 */
export const getArticleComments = <ThrowOnError extends boolean = false>(options: Options<GetArticleCommentsData, ThrowOnError>): RequestResult<GetArticleCommentsResponses, GetArticleCommentsErrors, ThrowOnError> => (options.client ?? client).get<GetArticleCommentsResponses, GetArticleCommentsErrors, ThrowOnError>({ url: '/articles/{slug}/comments', ...options });

/**
 * Create a comment for an article
 *
 * Create a comment for an article. Auth is required
 */
export const createArticleComment = <ThrowOnError extends boolean = false>(options: Options<CreateArticleCommentData, ThrowOnError>): RequestResult<CreateArticleCommentResponses, CreateArticleCommentErrors, ThrowOnError> => (options.client ?? client).post<CreateArticleCommentResponses, CreateArticleCommentErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/articles/{slug}/comments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a comment for an article
 *
 * Delete a comment for an article. Auth is required
 */
export const deleteArticleComment = <ThrowOnError extends boolean = false>(options: Options<DeleteArticleCommentData, ThrowOnError>): RequestResult<DeleteArticleCommentResponses, DeleteArticleCommentErrors, ThrowOnError> => (options.client ?? client).delete<DeleteArticleCommentResponses, DeleteArticleCommentErrors, ThrowOnError>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/articles/{slug}/comments/{id}',
    ...options
});
