// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type Article = {
    title: string;
    slug: string;
    description: string;
    body: string;
    createdAt: string;
    updatedAt: string;
    tagList: Array<string>;
    author: Profile;
    favorited: boolean;
    favoritesCount: number;
};

export type Comment = {
    id: number;
    body: string;
    createdAt: string;
    updatedAt: string;
    author: Profile;
};

export type HttpValidationProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
    errors?: {
        [key: string]: Array<string>;
    };
};

export type LoginUser = {
    email: string;
    password: string;
};

export type LoginUserRequest = {
    user: LoginUser;
};

export type MultipleArticlesResponse = {
    articles: Array<Article>;
    articlesCount: number;
};

export type MultipleCommentsResponse = {
    comments: Array<Comment>;
};

export type NewArticle = {
    title: string;
    description: string;
    body: string;
    tagList?: Array<string>;
};

export type NewArticleRequest = {
    article: NewArticle;
};

export type NewComment = {
    body: string;
};

export type NewCommentRequest = {
    comment: NewComment;
};

export type NewUser = {
    email: string;
    password: string;
    username: string;
};

export type NewUserRequest = {
    user: NewUser;
};

export type Profile = {
    username: string;
    bio?: null | string;
    image?: null | string;
    following?: boolean;
};

export type ProfileResponse = {
    profile: Profile;
};

export type SingleArticleResponse = {
    article: Article;
};

export type SingleCommentResponse = {
    comment: Comment;
};

export type TagsResponse = {
    tags: Array<string>;
};

export type UpdateArticle = {
    title?: null | string;
    description?: null | string;
    body?: null | string;
};

export type UpdateArticleRequest = {
    article: UpdateArticle;
};

export type UpdateUser = {
    username?: null | string;
    email?: null | string;
    bio?: null | string;
    image?: null | string;
};

export type UpdateUserRequest = {
    user: UpdateUser;
};

export type User = {
    email: string;
    username: string;
    bio?: null | string;
    image?: null | string;
    token: string;
};

export type UserResponse = {
    user: User;
};

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type GetCurrentUserResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type UpdateCurrentUserData = {
    /**
     * User details to update. At least <strong>one</strong> field is required.
     */
    body: UpdateUserRequest;
    path?: never;
    query?: never;
    url: '/user';
};

export type UpdateCurrentUserErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type UpdateCurrentUserError = UpdateCurrentUserErrors[keyof UpdateCurrentUserErrors];

export type UpdateCurrentUserResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type UpdateCurrentUserResponse = UpdateCurrentUserResponses[keyof UpdateCurrentUserResponses];

export type CreateUserData = {
    /**
     * Details of the new user to register
     */
    body: NewUserRequest;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type LoginData = {
    /**
     * Credentials to use
     */
    body: LoginUserRequest;
    path?: never;
    query?: never;
    url: '/users/login';
};

export type LoginErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetProfileByUsernameData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/profiles/{username}';
};

export type GetProfileByUsernameResponses = {
    /**
     * OK
     */
    200: ProfileResponse;
};

export type GetProfileByUsernameResponse = GetProfileByUsernameResponses[keyof GetProfileByUsernameResponses];

export type UnfollowUserByUsernameData = {
    body?: never;
    path: {
        /**
         * Username of the profile you want to unfollow
         */
        username: string;
    };
    query?: never;
    url: '/profiles/{username}/follow';
};

export type UnfollowUserByUsernameResponses = {
    /**
     * OK
     */
    200: ProfileResponse;
};

export type UnfollowUserByUsernameResponse = UnfollowUserByUsernameResponses[keyof UnfollowUserByUsernameResponses];

export type FollowUserByUsernameData = {
    body?: never;
    path: {
        /**
         * Username of the profile you want to follow
         */
        username: string;
    };
    query?: never;
    url: '/profiles/{username}/follow';
};

export type FollowUserByUsernameResponses = {
    /**
     * OK
     */
    200: ProfileResponse;
};

export type FollowUserByUsernameResponse = FollowUserByUsernameResponses[keyof FollowUserByUsernameResponses];

export type GetTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tags';
};

export type GetTagsResponses = {
    /**
     * OK
     */
    200: TagsResponse;
};

export type GetTagsResponse = GetTagsResponses[keyof GetTagsResponses];

export type GetArticlesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by author (username)
         */
        author?: string;
        /**
         * Filter by favorites of a user (username)
         */
        favorited?: string;
        /**
         * Filter by tag
         */
        tag?: string;
        /**
         * Limit number of articles returned (default is 20)
         */
        limit?: number;
        /**
         * Offset/skip number of articles (default is 0)
         */
        offset?: number;
    };
    url: '/articles';
};

export type GetArticlesResponses = {
    /**
     * OK
     */
    200: MultipleArticlesResponse;
};

export type GetArticlesResponse = GetArticlesResponses[keyof GetArticlesResponses];

export type CreateArticleData = {
    /**
     * Article to create
     */
    body: NewArticleRequest;
    path?: never;
    query?: never;
    url: '/articles';
};

export type CreateArticleErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type CreateArticleError = CreateArticleErrors[keyof CreateArticleErrors];

export type CreateArticleResponses = {
    /**
     * OK
     */
    200: SingleArticleResponse;
};

export type CreateArticleResponse = CreateArticleResponses[keyof CreateArticleResponses];

export type GetArticlesFeedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit number of articles returned (default is 20)
         */
        limit?: number;
        /**
         * Offset/skip number of articles (default is 0)
         */
        offset?: number;
    };
    url: '/articles/feed';
};

export type GetArticlesFeedResponses = {
    /**
     * OK
     */
    200: MultipleArticlesResponse;
};

export type GetArticlesFeedResponse = GetArticlesFeedResponses[keyof GetArticlesFeedResponses];

export type DeleteArticleData = {
    body?: never;
    path: {
        /**
         * Slug of the article to delete
         */
        slug: string;
    };
    query?: never;
    url: '/articles/{slug}';
};

export type DeleteArticleResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetArticleData = {
    body?: never;
    path: {
        /**
         * Slug of the article to get
         */
        slug: string;
    };
    query?: never;
    url: '/articles/{slug}';
};

export type GetArticleResponses = {
    /**
     * OK
     */
    200: SingleArticleResponse;
};

export type GetArticleResponse = GetArticleResponses[keyof GetArticleResponses];

export type UpdateArticleData = {
    /**
     * Article to update
     */
    body: UpdateArticleRequest;
    path: {
        /**
         * Slug of the article to update
         */
        slug: string;
    };
    query?: never;
    url: '/articles/{slug}';
};

export type UpdateArticleErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type UpdateArticleError = UpdateArticleErrors[keyof UpdateArticleErrors];

export type UpdateArticleResponses = {
    /**
     * OK
     */
    200: SingleArticleResponse;
};

export type UpdateArticleResponse = UpdateArticleResponses[keyof UpdateArticleResponses];

export type DeleteArticleFavoriteData = {
    body?: never;
    path: {
        /**
         * Slug of the article that you want to unfavorite
         */
        slug: string;
    };
    query?: never;
    url: '/articles/{slug}/favorite';
};

export type DeleteArticleFavoriteResponses = {
    /**
     * OK
     */
    200: SingleArticleResponse;
};

export type DeleteArticleFavoriteResponse = DeleteArticleFavoriteResponses[keyof DeleteArticleFavoriteResponses];

export type CreateArticleFavoriteData = {
    body?: never;
    path: {
        /**
         * Slug of the article that you want to favorite
         */
        slug: string;
    };
    query?: never;
    url: '/articles/{slug}/favorite';
};

export type CreateArticleFavoriteResponses = {
    /**
     * OK
     */
    200: SingleArticleResponse;
};

export type CreateArticleFavoriteResponse = CreateArticleFavoriteResponses[keyof CreateArticleFavoriteResponses];

export type GetArticleCommentsData = {
    body?: never;
    path: {
        /**
         * Slug of the article that you want to get comments for
         */
        slug: string;
    };
    query?: never;
    url: '/articles/{slug}/comments';
};

export type GetArticleCommentsResponses = {
    /**
     * OK
     */
    200: MultipleCommentsResponse;
};

export type GetArticleCommentsResponse = GetArticleCommentsResponses[keyof GetArticleCommentsResponses];

export type CreateArticleCommentData = {
    body: NewCommentRequest;
    path: {
        /**
         * Slug of the article that you want to create a comments for
         */
        slug: string;
    };
    query?: never;
    url: '/articles/{slug}/comments';
};

export type CreateArticleCommentErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type CreateArticleCommentError = CreateArticleCommentErrors[keyof CreateArticleCommentErrors];

export type CreateArticleCommentResponses = {
    /**
     * OK
     */
    200: SingleCommentResponse;
};

export type CreateArticleCommentResponse = CreateArticleCommentResponses[keyof CreateArticleCommentResponses];

export type DeleteArticleCommentData = {
    body?: never;
    path: {
        /**
         * Slug of the article that you want to delete a comments for
         */
        slug: string;
        /**
         * ID of the comment you want to delete
         */
        commentId: number;
    };
    query?: never;
    url: '/articles/{slug}/comments/{commentId}';
};

export type DeleteArticleCommentResponses = {
    /**
     * OK
     */
    200: unknown;
};
