/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/articles": {
    /** Get most recent articles globally. Use query parameters to filter results. Auth is optional */
    get: operations["GetArticles"]
    /** Create an article. Auth is required */
    post: operations["CreateArticle"]
  }
  "/articles/feed": {
    /** Get most recent articles from users you follow. Use query parameters to limit. Auth is required */
    get: operations["GetArticlesFeed"]
  }
  "/articles/{slug}": {
    /** Get an article. Auth not required */
    get: operations["GetArticle"]
    /** Update an article. Auth is required */
    put: operations["UpdateArticle"]
    /** Delete an article. Auth is required */
    delete: operations["DeleteArticle"]
  }
  "/articles/{slug}/comments": {
    /** Get the comments for an article. Auth is optional */
    get: operations["GetArticleComments"]
    /** Create a comment for an article. Auth is required */
    post: operations["CreateArticleComment"]
  }
  "/articles/{slug}/comments/{commentId}": {
    /** Delete a comment for an article. Auth is required */
    delete: operations["DeleteArticleComment"]
  }
  "/articles/{slug}/favorite": {
    /** Favorite an article. Auth is required */
    post: operations["CreateArticleFavorite"]
    /** Unfavorite an article. Auth is required */
    delete: operations["DeleteArticleFavorite"]
  }
  "/profiles/celeb_{username}": {
    /** Get a profile of a user of the system. Auth is optional */
    get: operations["GetProfileByUsername"]
  }
  "/profiles/celeb_{username}/follow": {
    /** Follow a user by username */
    post: operations["FollowUserByUsername"]
    /** Unfollow a user by username */
    delete: operations["UnfollowUserByUsername"]
  }
  "/tags": {
    /** Get tags. Auth not required */
    get: operations["GetTags"]
  }
  "/user": {
    /** Gets the currently logged-in user */
    get: operations["GetCurrentUser"]
    /** Updated user information for current user */
    put: operations["UpdateCurrentUser"]
  }
  "/users": {
    /** Register a new user */
    post: operations["CreateUser"]
  }
  "/users/login": {
    /** Login for existing user */
    post: operations["Login"]
  }
}

export interface components {
  schemas: {
    Article: {
      title: string
      slug: string
      description: string
      body: string
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
      tagList: string[]
      author: components["schemas"]["Profile"]
      favorited: boolean
      /** Format: int32 */
      favoritesCount: number
    }
    Comment: {
      /** Format: int32 */
      id: number
      body: string
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
      author: components["schemas"]["Profile"]
    }
    LoginUser: {
      email: string
      password: string
    }
    LoginUserRequest: {
      user: components["schemas"]["LoginUser"]
    }
    MultipleArticlesResponse: {
      articles: components["schemas"]["Article"][]
      /** Format: int32 */
      articlesCount: number
    }
    MultipleCommentsResponse: {
      comments: components["schemas"]["Comment"][]
    }
    NewArticle: {
      title: string
      description: string
      body: string
      tagList?: string[] | null
    }
    NewArticleRequest: {
      article: components["schemas"]["NewArticle"]
    }
    NewComment: {
      body: string
    }
    NewCommentRequest: {
      comment: components["schemas"]["NewComment"]
    }
    NewUser: {
      email: string
      password: string
      username: string
    }
    NewUserRequest: {
      user: components["schemas"]["NewUser"]
    }
    Profile: {
      username: string
      bio: string
      image: string
      following: boolean
    }
    ProfileResponse: {
      profile: components["schemas"]["Profile"]
    }
    SingleArticleResponse: {
      article: components["schemas"]["Article"]
    }
    SingleCommentResponse: {
      comment: components["schemas"]["Comment"]
    }
    TagsResponse: {
      tags: string[]
    }
    UpdateArticle: {
      title?: string | null
      description?: string | null
      body?: string | null
    }
    UpdateArticleRequest: {
      article: components["schemas"]["UpdateArticle"]
    }
    UpdateUser: {
      username?: string | null
      email?: string | null
      bio?: string | null
      image?: string | null
    }
    UpdateUserRequest: {
      user: components["schemas"]["UpdateUser"]
    }
    User: {
      email: string
      username: string
      bio: string
      image: string
      token: string
    }
    UserResponse: {
      user: components["schemas"]["User"]
    }
    ValidationProblemDetails: {
      type?: string | null
      title?: string | null
      /** Format: int32 */
      status?: number | null
      detail?: string | null
      instance?: string | null
      errors: { [key: string]: string[] }
    } & { [key: string]: unknown }
  }
}

export interface operations {
  /** Get most recent articles globally. Use query parameters to filter results. Auth is optional */
  GetArticles: {
    parameters: {
      query: {
        /** Filter by author (username) */
        author?: string
        /** Filter by favorites of a user (username) */
        favorited?: string
        /** Filter by tag */
        tag?: string
        /** Limit number of articles returned (default is 20) */
        limit?: number
        /** Offset/skip number of articles (default is 0) */
        offset?: number
      }
    }
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["MultipleArticlesResponse"]
          "application/json": components["schemas"]["MultipleArticlesResponse"]
          "text/json": components["schemas"]["MultipleArticlesResponse"]
        }
      }
    }
  }
  /** Create an article. Auth is required */
  CreateArticle: {
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["SingleArticleResponse"]
          "application/json": components["schemas"]["SingleArticleResponse"]
          "text/json": components["schemas"]["SingleArticleResponse"]
        }
      }
      /** Bad Request */
      400: {
        content: {
          "text/plain": components["schemas"]["ValidationProblemDetails"]
          "application/json": components["schemas"]["ValidationProblemDetails"]
          "text/json": components["schemas"]["ValidationProblemDetails"]
        }
      }
      /** Unauthorized */
      401: unknown
      /** Forbidden */
      403: unknown
    }
    /** Article to create */
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewArticleRequest"]
        "text/json": components["schemas"]["NewArticleRequest"]
        "application/*+json": components["schemas"]["NewArticleRequest"]
      }
    }
  }
  /** Get most recent articles from users you follow. Use query parameters to limit. Auth is required */
  GetArticlesFeed: {
    parameters: {
      query: {
        /** Limit number of articles returned (default is 20) */
        limit?: number
        /** Offset/skip number of articles (default is 0) */
        offset?: number
      }
    }
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["MultipleArticlesResponse"]
          "application/json": components["schemas"]["MultipleArticlesResponse"]
          "text/json": components["schemas"]["MultipleArticlesResponse"]
        }
      }
      /** Unauthorized */
      401: unknown
      /** Forbidden */
      403: unknown
    }
  }
  /** Get an article. Auth not required */
  GetArticle: {
    parameters: {
      path: {
        /** Slug of the article to get */
        slug: string
      }
    }
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["SingleArticleResponse"]
          "application/json": components["schemas"]["SingleArticleResponse"]
          "text/json": components["schemas"]["SingleArticleResponse"]
        }
      }
    }
  }
  /** Update an article. Auth is required */
  UpdateArticle: {
    parameters: {
      path: {
        /** Slug of the article to update */
        slug: string
      }
    }
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["SingleArticleResponse"]
          "application/json": components["schemas"]["SingleArticleResponse"]
          "text/json": components["schemas"]["SingleArticleResponse"]
        }
      }
      /** Bad Request */
      400: {
        content: {
          "text/plain": components["schemas"]["ValidationProblemDetails"]
          "application/json": components["schemas"]["ValidationProblemDetails"]
          "text/json": components["schemas"]["ValidationProblemDetails"]
        }
      }
      /** Unauthorized */
      401: unknown
      /** Forbidden */
      403: unknown
    }
    /** Article to update */
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateArticleRequest"]
        "text/json": components["schemas"]["UpdateArticleRequest"]
        "application/*+json": components["schemas"]["UpdateArticleRequest"]
      }
    }
  }
  /** Delete an article. Auth is required */
  DeleteArticle: {
    parameters: {
      path: {
        /** Slug of the article to delete */
        slug: string
      }
    }
    responses: {
      /** Success */
      200: unknown
      /** Unauthorized */
      401: unknown
      /** Forbidden */
      403: unknown
    }
  }
  /** Get the comments for an article. Auth is optional */
  GetArticleComments: {
    parameters: {
      path: {
        /** Slug of the article that you want to get comments for */
        slug: string
      }
    }
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["MultipleCommentsResponse"]
          "application/json": components["schemas"]["MultipleCommentsResponse"]
          "text/json": components["schemas"]["MultipleCommentsResponse"]
        }
      }
    }
  }
  /** Create a comment for an article. Auth is required */
  CreateArticleComment: {
    parameters: {
      path: {
        /** Slug of the article that you want to create a comment for */
        slug: string
      }
    }
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["SingleCommentResponse"]
          "application/json": components["schemas"]["SingleCommentResponse"]
          "text/json": components["schemas"]["SingleCommentResponse"]
        }
      }
      /** Bad Request */
      400: {
        content: {
          "text/plain": components["schemas"]["ValidationProblemDetails"]
          "application/json": components["schemas"]["ValidationProblemDetails"]
          "text/json": components["schemas"]["ValidationProblemDetails"]
        }
      }
      /** Unauthorized */
      401: unknown
      /** Forbidden */
      403: unknown
    }
    /** Comment you want to create */
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewCommentRequest"]
        "text/json": components["schemas"]["NewCommentRequest"]
        "application/*+json": components["schemas"]["NewCommentRequest"]
      }
    }
  }
  /** Delete a comment for an article. Auth is required */
  DeleteArticleComment: {
    parameters: {
      path: {
        /** Slug of the article that you want to delete a comment for */
        slug: string
        /** ID of the comment you want to delete */
        commentId: number
      }
    }
    responses: {
      /** Success */
      200: unknown
      /** Unauthorized */
      401: unknown
      /** Forbidden */
      403: unknown
    }
  }
  /** Favorite an article. Auth is required */
  CreateArticleFavorite: {
    parameters: {
      path: {
        /** Slug of the article that you want to favorite */
        slug: string
      }
    }
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["SingleArticleResponse"]
          "application/json": components["schemas"]["SingleArticleResponse"]
          "text/json": components["schemas"]["SingleArticleResponse"]
        }
      }
      /** Unauthorized */
      401: unknown
      /** Forbidden */
      403: unknown
    }
  }
  /** Unfavorite an article. Auth is required */
  DeleteArticleFavorite: {
    parameters: {
      path: {
        /** Slug of the article that you want to unfavorite */
        slug: string
      }
    }
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["SingleArticleResponse"]
          "application/json": components["schemas"]["SingleArticleResponse"]
          "text/json": components["schemas"]["SingleArticleResponse"]
        }
      }
      /** Unauthorized */
      401: unknown
      /** Forbidden */
      403: unknown
    }
  }
  /** Get a profile of a user of the system. Auth is optional */
  GetProfileByUsername: {
    parameters: {
      path: {
        /** Username of the profile to get */
        username: string
      }
    }
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["ProfileResponse"]
          "application/json": components["schemas"]["ProfileResponse"]
          "text/json": components["schemas"]["ProfileResponse"]
        }
      }
    }
  }
  /** Follow a user by username */
  FollowUserByUsername: {
    parameters: {
      path: {
        /** Username of the profile you want to follow */
        username: string
      }
    }
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["ProfileResponse"]
          "application/json": components["schemas"]["ProfileResponse"]
          "text/json": components["schemas"]["ProfileResponse"]
        }
      }
      /** Unauthorized */
      401: unknown
      /** Forbidden */
      403: unknown
    }
  }
  /** Unfollow a user by username */
  UnfollowUserByUsername: {
    parameters: {
      path: {
        /** Username of the profile you want to unfollow */
        username: string
      }
    }
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["ProfileResponse"]
          "application/json": components["schemas"]["ProfileResponse"]
          "text/json": components["schemas"]["ProfileResponse"]
        }
      }
      /** Unauthorized */
      401: unknown
      /** Forbidden */
      403: unknown
    }
  }
  /** Get tags. Auth not required */
  GetTags: {
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["TagsResponse"]
          "application/json": components["schemas"]["TagsResponse"]
          "text/json": components["schemas"]["TagsResponse"]
        }
      }
    }
  }
  /** Gets the currently logged-in user */
  GetCurrentUser: {
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["UserResponse"]
          "application/json": components["schemas"]["UserResponse"]
          "text/json": components["schemas"]["UserResponse"]
        }
      }
      /** Unauthorized */
      401: unknown
      /** Forbidden */
      403: unknown
    }
  }
  /** Updated user information for current user */
  UpdateCurrentUser: {
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["UserResponse"]
          "application/json": components["schemas"]["UserResponse"]
          "text/json": components["schemas"]["UserResponse"]
        }
      }
      /** Bad Request */
      400: {
        content: {
          "text/plain": components["schemas"]["ValidationProblemDetails"]
          "application/json": components["schemas"]["ValidationProblemDetails"]
          "text/json": components["schemas"]["ValidationProblemDetails"]
        }
      }
      /** Unauthorized */
      401: unknown
      /** Forbidden */
      403: unknown
    }
    /** User details to update. At least <strong>one</strong> field is required. */
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserRequest"]
        "text/json": components["schemas"]["UpdateUserRequest"]
        "application/*+json": components["schemas"]["UpdateUserRequest"]
      }
    }
  }
  /** Register a new user */
  CreateUser: {
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["UserResponse"]
          "application/json": components["schemas"]["UserResponse"]
          "text/json": components["schemas"]["UserResponse"]
        }
      }
      /** Bad Request */
      400: {
        content: {
          "text/plain": components["schemas"]["ValidationProblemDetails"]
          "application/json": components["schemas"]["ValidationProblemDetails"]
          "text/json": components["schemas"]["ValidationProblemDetails"]
        }
      }
    }
    /** Details of the new user to register */
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewUserRequest"]
        "text/json": components["schemas"]["NewUserRequest"]
        "application/*+json": components["schemas"]["NewUserRequest"]
      }
    }
  }
  /** Login for existing user */
  Login: {
    responses: {
      /** Success */
      200: {
        content: {
          "text/plain": components["schemas"]["UserResponse"]
          "application/json": components["schemas"]["UserResponse"]
          "text/json": components["schemas"]["UserResponse"]
        }
      }
      /** Bad Request */
      400: {
        content: {
          "text/plain": components["schemas"]["ValidationProblemDetails"]
          "application/json": components["schemas"]["ValidationProblemDetails"]
          "text/json": components["schemas"]["ValidationProblemDetails"]
        }
      }
    }
    /** Credentials to use */
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginUserRequest"]
        "text/json": components["schemas"]["LoginUserRequest"]
        "application/*+json": components["schemas"]["LoginUserRequest"]
      }
    }
  }
}
