// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ArticlesNav: typeof import('./components/ArticlesNav.vue')['default']
    OffsetPagination: typeof import('./components/OffsetPagination.vue')['default']
    Paginator: typeof import('./components/Paginator.vue')['default']
    PostCard: typeof import('./components/PostCard.vue')['default']
    PostsList: typeof import('./components/PostsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsList: typeof import('./components/TagsList.vue')['default']
  }
}

export {}
