// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlertMessage: typeof import('./components/AlertMessage.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ArticlesNav: typeof import('./components/ArticlesNav.vue')['default']
    AuthorLayout: typeof import('./components/AuthorLayout.vue')['default']
    CommentCard: typeof import('./components/CommentCard.vue')['default']
    CommentNew: typeof import('./components/CommentNew.vue')['default']
    FavoriteArticle: typeof import('./components/Actions/FavoriteArticle.vue')['default']
    FollowProfile: typeof import('./components/Actions/FollowProfile.vue')['default']
    HomeLayout: typeof import('./components/HomeLayout.vue')['default']
    IconButton: typeof import('./components/IconButton.vue')['default']
    MarkdownViewer: typeof import('./components/MarkdownViewer.vue')['default']
    OffsetPagination: typeof import('./components/OffsetPagination.vue')['default']
    PostAuthor: typeof import('./components/PostAuthor.vue')['default']
    PostCard: typeof import('./components/PostCard.vue')['default']
    PostsList: typeof import('./components/PostsList.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuccessMessage: typeof import('./components/SuccessMessage.vue')['default']
    TagInput: typeof import('./components/Inputs/TagInput.vue')['default']
    TagsList: typeof import('./components/TagsList.vue')['default']
  }
}

export {}
